sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qg1J12XUUYRrQBpyWieejjoSVggfdyz5xk+Uars5lRpCdQ6JJ2L8sy/Vt9nGl7z7Ez47R+W3EQc1fpShQLK4CWrJ5S9oBYo4zAeHcoNSBRhrYB5MP7BzfUkPGoHPny4w8dJ0n0sW80C9dRl0nACjZxdVZtbB6/ELli7pJmuG4QEqCgxTyIINZCiBO7sLQZYaUzUO+6wv+vfKd8rB/R3ZB5j3MqZUqRME2R/gHqi/kkqZNOW/yJ1/8WuqWSW0qSq7jRDQBiTs5QLCEWsLGoseLdaPiUp84/xdXKBgIJ+b+Mn/9PODJfqXThWpA7fRCz3+K/1c176fOpA7oDB3mnISP2jOaWAMebUvFzTEDpb84ayGXqkbUls+y6PjmOiHPyPUKoIZinaIRHjHLMs8tR6UxtUp6Ho2xo8R8zfMQx5hjsaPiqB/mX+hF5Hs4LNU7VFXjcHFfcfBieEcP6GJIM+EGtWTOoUdO6fV75O1K/UfwW2xGj8ohpFIXup55C+eG9mYkd+y5TYDaMoxcJcH6F717U0w/FzG7083DvSgvAJGjGxbKb6/8S3NtjFLN/uw3lcJtntHtxMaUbQEtTKCpGMAvAKgbZpyn4KaxpiQDow5XM2t3DvqAp7Lf5Nb5XUAWHxlVhw6+HdBNAH8Qta4Uehl2xKyJa+fRjyjsw589u/dG4s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Intrusion-of-Jimmy_4075
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy